kind: "BuildConfig"
apiVersion: "v1"
metadata:
  labels:
    build: tasks-pipeline
  name: "tasks-pipeline"
spec:
  source:
    type: "Git"
    git:
      uri: "https://homework-gitea.apps.shared.na.openshift.opentlc.com/dliderma-redhat.com/homework.git"
    contextDir: openshift-tasks
    sourceSecret:
      name: homework-gitea
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
      - name: CLUSTER
        value: shared.na.openshift.opentlc.com
      - name: GUID
        value: 84ae
      - name: REPO
        value: https://homework-gitea.apps.shared.na.openshift.opentlc.com/dliderma-redhat.com/homework.git
